#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WS.Mobile.WorkOrders.Resource", IsApplication=true)]

namespace WS.Mobile.WorkOrders
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int rotate_center = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int Black = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Gray = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int Red = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int SeaShell = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int Yellow = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int brand_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int refresh_btn_25 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int refresh_btn_25_Grey = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001b
			public const int additionalWorkText = 2131296283;
			
			// aapt resource value: 0x7f09002f
			public const int attributeAddButton = 2131296303;
			
			// aapt resource value: 0x7f090019
			public const int branchName = 2131296281;
			
			// aapt resource value: 0x7f090009
			public const int employeeBranch = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int employeeNumber = 2131296264;
			
			// aapt resource value: 0x7f090020
			public const int frameLayout1 = 2131296288;
			
			// aapt resource value: 0x7f090002
			public const int loginButton = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int loginEmployeeNumberText = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int loginPinText = 2131296257;
			
			// aapt resource value: 0x7f090035
			public const int menu_cancel = 2131296309;
			
			// aapt resource value: 0x7f090031
			public const int menu_changeServer = 2131296305;
			
			// aapt resource value: 0x7f090033
			public const int menu_logout = 2131296307;
			
			// aapt resource value: 0x7f090034
			public const int menu_save = 2131296308;
			
			// aapt resource value: 0x7f090032
			public const int menu_version = 2131296306;
			
			// aapt resource value: 0x7f090006
			public const int unitAddButton = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int unitNumber = 2131296263;
			
			// aapt resource value: 0x7f090004
			public const int unitNumberPart1Text = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int unitNumberPart2Text = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int unitsTable = 2131296259;
			
			// aapt resource value: 0x7f09000a
			public const int workOrderActivitiesTable = 2131296266;
			
			// aapt resource value: 0x7f090017
			public const int workOrderActivityAddButton = 2131296279;
			
			// aapt resource value: 0x7f090012
			public const int workOrderActivityAddCheck = 2131296274;
			
			// aapt resource value: 0x7f09000d
			public const int workOrderActivityExteriorRadio = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int workOrderActivityInteriorRadio = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int workOrderActivityLocationGroup = 2131296267;
			
			// aapt resource value: 0x7f090013
			public const int workOrderActivityRemoveCheck = 2131296275;
			
			// aapt resource value: 0x7f090015
			public const int workOrderActivityRepairCheck = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int workOrderActivityReplaceCheck = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int workOrderActivityServiceCheck = 2131296278;
			
			// aapt resource value: 0x7f090011
			public const int workOrderActivityTypeGroup = 2131296273;
			
			// aapt resource value: 0x7f09000e
			public const int workOrderActivityTypeSpinner = 2131296270;
			
			// aapt resource value: 0x7f090029
			public const int workOrderBoxLengthLabel = 2131296297;
			
			// aapt resource value: 0x7f09002b
			public const int workOrderBoxWidthLabel = 2131296299;
			
			// aapt resource value: 0x7f090023
			public const int workOrderBranchNumberLabel = 2131296291;
			
			// aapt resource value: 0x7f090010
			public const int workOrderDamageBillingPercentageNumber = 2131296272;
			
			// aapt resource value: 0x7f090024
			public const int workOrderDateAcquiredLabel = 2131296292;
			
			// aapt resource value: 0x7f09002c
			public const int workOrderDescriptionLabel = 2131296300;
			
			// aapt resource value: 0x7f09002e
			public const int workOrderDescriptionLabel2 = 2131296302;
			
			// aapt resource value: 0x7f090030
			public const int workOrderDescriptionTable = 2131296304;
			
			// aapt resource value: 0x7f090026
			public const int workOrderEquipmentClassLabel = 2131296294;
			
			// aapt resource value: 0x7f09001c
			public const int workOrderImagesTable = 2131296284;
			
			// aapt resource value: 0x7f090027
			public const int workOrderManufacturerLabel = 2131296295;
			
			// aapt resource value: 0x7f090025
			public const int workOrderManufacturerSerialNumberLabel = 2131296293;
			
			// aapt resource value: 0x7f090028
			public const int workOrderModelYearLabel = 2131296296;
			
			// aapt resource value: 0x7f090021
			public const int workOrderPartsAddButton = 2131296289;
			
			// aapt resource value: 0x7f09001e
			public const int workOrderPartsTable = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int workOrderPartsTypeSpinner = 2131296287;
			
			// aapt resource value: 0x7f09000f
			public const int workOrderQtyNumber = 2131296271;
			
			// aapt resource value: 0x7f09001a
			public const int workOrderRevenueBranchSpinner = 2131296282;
			
			// aapt resource value: 0x7f090022
			public const int workOrderSerialNumberLabel = 2131296290;
			
			// aapt resource value: 0x7f09002a
			public const int workOrderSquareFootageLabel = 2131296298;
			
			// aapt resource value: 0x7f09001d
			public const int workOrderTakePhotoButton = 2131296285;
			
			// aapt resource value: 0x7f09002d
			public const int workOrderTotalLengthLabel = 2131296301;
			
			// aapt resource value: 0x7f090018
			public const int workOrderTypeSpinner = 2131296280;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int menu_loggedInUser = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int workOrder = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int workOrderActivitiesTab = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int workOrderDetailTab = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int workOrderImagesTab = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int workOrderPartsTab = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int workOrderUnitAttributesTab = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int login_activity = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int main_activity = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int workorder_activity = 2131230722;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050020
			public const int attributeAddButtonText = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int attributeChangeText = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int attributeDeleteButtonText = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int attributeEditButtonText = 2131034142;
			
			// aapt resource value: 0x7f050002
			public const int menu_cancel = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int menu_changeServer = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int menu_logout = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int menu_save = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int menu_version = 2131034116;
			
			// aapt resource value: 0x7f05001c
			public const int unit_Off_Rent = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int unit_On_Rent = 2131034141;
			
			// aapt resource value: 0x7f05000f
			public const int units_add = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int units_upload = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int units_uploadAll = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int units_uploadOffRent = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int units_uploadOnRent = 2131034125;
			
			// aapt resource value: 0x7f050012
			public const int workOrder_add = 2131034130;
			
			// aapt resource value: 0x7f050019
			public const int workOrder_cancel = 2131034137;
			
			// aapt resource value: 0x7f050017
			public const int workOrder_damage = 2131034135;
			
			// aapt resource value: 0x7f05001b
			public const int workOrder_exterior = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int workOrder_interior = 2131034138;
			
			// aapt resource value: 0x7f050014
			public const int workOrder_remove = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int workOrder_repair = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int workOrder_replace = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int workOrder_save = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int workOrder_service = 2131034134;
			
			// aapt resource value: 0x7f050008
			public const int workOrder_tab_activities = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int workOrder_tab_attributes = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int workOrder_tab_details = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int workOrder_tab_images = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int workOrder_tab_parts = 2131034121;
			
			// aapt resource value: 0x7f050010
			public const int workOrder_takePhoto = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int workOrder_unknown = 2131034129;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int WS_Theme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int WS_Theme_ButtonBar = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int WS_Theme_FieldName = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int WS_Theme_OMBButton = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int WS_Theme_TableFieldName = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int WS_Theme_TableFieldValue = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int WS_Theme_TableHeader = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
