//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace WS20.SafetyAudit.FWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FormsIQWebServiceSoapBinding", Namespace="http://ws89nt/formsiq/services/FormsIQWebService")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Row))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Attribute))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FormFieldEx))]
    public partial class FormsIQWebServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback validateXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback submitFormOperationCompleted;
        
        private System.Threading.SendOrPostCallback submitForm1OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FormsIQWebServiceService() {
            this.Url = global::WS20.SafetyAudit.Properties.Settings.Default.Safety_Audit_FWS1_FormsIQWebServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event validateXMLCompletedEventHandler validateXMLCompleted;
        
        /// <remarks/>
        public event submitFormCompletedEventHandler submitFormCompleted;
        
        /// <remarks/>
        public event submitForm1CompletedEventHandler submitForm1Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://webservices.formsiq.feith.com", ResponseNamespace="http://ws89nt/formsiq/services/FormsIQWebService")]
        [return: System.Xml.Serialization.SoapElementAttribute("validateXMLReturn")]
        public bool validateXML(string contents) {
            object[] results = this.Invoke("validateXML", new object[] {
                        contents});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void validateXMLAsync(string contents) {
            this.validateXMLAsync(contents, null);
        }
        
        /// <remarks/>
        public void validateXMLAsync(string contents, object userState) {
            if ((this.validateXMLOperationCompleted == null)) {
                this.validateXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateXMLOperationCompleted);
            }
            this.InvokeAsync("validateXML", new object[] {
                        contents}, this.validateXMLOperationCompleted, userState);
        }
        
        private void OnvalidateXMLOperationCompleted(object arg) {
            if ((this.validateXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateXMLCompleted(this, new validateXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://webservices.formsiq.feith.com", ResponseNamespace="http://ws89nt/formsiq/services/FormsIQWebService")]
        [return: System.Xml.Serialization.SoapElementAttribute("submitFormReturn")]
        public string submitForm(FormsIQExternalData form, string theFieldName) {
            object[] results = this.Invoke("submitForm", new object[] {
                        form,
                        theFieldName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void submitFormAsync(FormsIQExternalData form, string theFieldName) {
            this.submitFormAsync(form, theFieldName, null);
        }
        
        /// <remarks/>
        public void submitFormAsync(FormsIQExternalData form, string theFieldName, object userState) {
            if ((this.submitFormOperationCompleted == null)) {
                this.submitFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitFormOperationCompleted);
            }
            this.InvokeAsync("submitForm", new object[] {
                        form,
                        theFieldName}, this.submitFormOperationCompleted, userState);
        }
        
        private void OnsubmitFormOperationCompleted(object arg) {
            if ((this.submitFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.submitFormCompleted(this, new submitFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="submitForm1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://webservices.formsiq.feith.com", ResponseNamespace="http://ws89nt/formsiq/services/FormsIQWebService")]
        [return: System.Xml.Serialization.SoapElementAttribute("submitFormReturn")]
        public string submitForm(FormsIQExternalData form) {
            object[] results = this.Invoke("submitForm1", new object[] {
                        form});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void submitForm1Async(FormsIQExternalData form) {
            this.submitForm1Async(form, null);
        }
        
        /// <remarks/>
        public void submitForm1Async(FormsIQExternalData form, object userState) {
            if ((this.submitForm1OperationCompleted == null)) {
                this.submitForm1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitForm1OperationCompleted);
            }
            this.InvokeAsync("submitForm1", new object[] {
                        form}, this.submitForm1OperationCompleted, userState);
        }
        
        private void OnsubmitForm1OperationCompleted(object arg) {
            if ((this.submitForm1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.submitForm1Completed(this, new submitForm1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:FormsIQWebService")]
    public partial class FormsIQExternalData {
        
        private FormFieldEx[] fieldListField;
        
        private FormInfo formInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public FormFieldEx[] fieldList {
            get {
                return this.fieldListField;
            }
            set {
                this.fieldListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public FormInfo formInfo {
            get {
                return this.formInfoField;
            }
            set {
                this.formInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SingleField))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ListField))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:FormsIQWebService")]
    public partial class FormFieldEx {
        
        private Attribute[] attributesField;
        
        private FieldIdentifier identifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Attribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public FieldIdentifier identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:FormsIQWebService")]
    public partial class Attribute {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:FormsIQWebService")]
    public partial class FormInfo {
        
        private Attribute[] attributesField;
        
        private string dataSourceField;
        
        private int formIdField;
        
        private string formNameField;
        
        private int formSetIdField;
        
        private FormFieldEx[] preformFieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Attribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dataSource {
            get {
                return this.dataSourceField;
            }
            set {
                this.dataSourceField = value;
            }
        }
        
        /// <remarks/>
        public int formId {
            get {
                return this.formIdField;
            }
            set {
                this.formIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string formName {
            get {
                return this.formNameField;
            }
            set {
                this.formNameField = value;
            }
        }
        
        /// <remarks/>
        public int formSetId {
            get {
                return this.formSetIdField;
            }
            set {
                this.formSetIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public FormFieldEx[] preformFields {
            get {
                return this.preformFieldsField;
            }
            set {
                this.preformFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:FormsIQWebService")]
    public partial class Row {
        
        private FormFieldEx[] columnsField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public FormFieldEx[] columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:FormsIQWebService")]
    public partial class FieldIdentifier {
        
        private int fieldSequenceField;
        
        private string parameterNameField;
        
        private string referenceNameField;
        
        /// <remarks/>
        public int fieldSequence {
            get {
                return this.fieldSequenceField;
            }
            set {
                this.fieldSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string parameterName {
            get {
                return this.parameterNameField;
            }
            set {
                this.parameterNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string referenceName {
            get {
                return this.referenceNameField;
            }
            set {
                this.referenceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:FormsIQWebService")]
    public partial class SingleField : FormFieldEx {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:FormsIQWebService")]
    public partial class ListField : FormFieldEx {
        
        private Row[] rowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Row[] rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void validateXMLCompletedEventHandler(object sender, validateXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validateXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void submitFormCompletedEventHandler(object sender, submitFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class submitFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal submitFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void submitForm1CompletedEventHandler(object sender, submitForm1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class submitForm1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal submitForm1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591