//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressBook
    {
        public decimal ID { get; set; }
        public string LongAddressNumber { get; set; }
        public string TaxID { get; set; }
        public string NameAlpha { get; set; }
        public string DescriptionCompressed { get; set; }
        public string BusinessUnit { get; set; }
        public string IndustryClassificationCode { get; set; }
        public string Language { get; set; }
        public string SearchType { get; set; }
        public string CreditMessage { get; set; }
        public string PersonCorporationCode { get; set; }
        public string ARAPNettingIndicator { get; set; }
        public string HRMRecordsExist { get; set; }
        public string AddressType4 { get; set; }
        public string AddressType5 { get; set; }
        public string AddressTypePayables { get; set; }
        public string AddressTypeReceivables { get; set; }
        public string AddressTypeCodePurchaser { get; set; }
        public string AddressBookMiscellaneousCodefuture { get; set; }
        public string AddressTypeEmployee { get; set; }
        public string SubledgerInactiveCode { get; set; }
        public Nullable<int> DateBeginningEffective { get; set; }
        public Nullable<decimal> AddressNumber1st { get; set; }
        public Nullable<decimal> AddressNumber2nd { get; set; }
        public Nullable<decimal> AddressNumber3rd { get; set; }
        public Nullable<decimal> AddressNumber4th { get; set; }
        public Nullable<decimal> AddressNumber5th { get; set; }
        public Nullable<decimal> FactorSpecialPayee { get; set; }
        public string CategoryCodeAddressBook01 { get; set; }
        public string CategoryCodeAddressBook02 { get; set; }
        public string CategoryCodeAddressBook03 { get; set; }
        public string CategoryCodeAddressBook04 { get; set; }
        public string CategoryCodeAddressBook05 { get; set; }
        public string SupplierClass { get; set; }
        public string ReportIng1099 { get; set; }
        public string W9Branch { get; set; }
        public string W9Compliance { get; set; }
        public string RiskManagementFlag { get; set; }
        public string AllowCommission { get; set; }
        public string CustomerType { get; set; }
        public string OrderType { get; set; }
        public string ContractType { get; set; }
        public string BillFrequency { get; set; }
        public string TrailerNewUsed { get; set; }
        public string MailFlagSpecialHandling { get; set; }
        public string CategoryCodeAddressBook18 { get; set; }
        public string CategoryCodeAddressBook19 { get; set; }
        public string CategoryCodeAddressBook20 { get; set; }
        public string CategoryCodeAddressBook21 { get; set; }
        public string CategoryCodeAddressBook22 { get; set; }
        public string CategoryCodeAddressBook23 { get; set; }
        public string CategoryCodeAddressBook24 { get; set; }
        public string CategoryCodeAddressBook25 { get; set; }
        public string CategoryCodeAddressBook26 { get; set; }
        public string CategoryCodeAddressBook27 { get; set; }
        public string CategoryCodeAddressBook28 { get; set; }
        public string CategoryCodeAddressBook29 { get; set; }
        public string CategoryCodeAddressBook30 { get; set; }
        public string GLBankAccount { get; set; }
        public Nullable<decimal> TimeScheduledIn { get; set; }
        public Nullable<int> DateScheduledIn { get; set; }
        public string ActionMessageControl { get; set; }
        public string NameRemark { get; set; }
        public string CertificateTaxExemption { get; set; }
        public string TaxIDAdditionalIndividual { get; set; }
        public string SecondaryAlphaName { get; set; }
        public string UserReservedCode { get; set; }
        public Nullable<int> UserReservedDate { get; set; }
        public Nullable<decimal> UserReservedAmount { get; set; }
        public Nullable<decimal> UserReservedNumber { get; set; }
        public string UserReservedReference { get; set; }
        public string UserID { get; set; }
        public string ProgramID { get; set; }
        public Nullable<int> DateUpdated { get; set; }
        public string WorkStationID { get; set; }
        public Nullable<decimal> TimeLastUpdated { get; set; }
        public string PurgeFlag { get; set; }
        public string ShortcutClientTypefuture { get; set; }
        public string Ticker { get; set; }
        public string StockExchange { get; set; }
        public string DUNSNumber { get; set; }
        public string ClassificationCode01 { get; set; }
        public string ClassificationCode02 { get; set; }
        public string ClassificationCode03 { get; set; }
        public string ClassificationCode04 { get; set; }
        public string ClassificationCode05 { get; set; }
        public Nullable<decimal> NumberOfEmployee { get; set; }
        public Nullable<decimal> GrowthRate { get; set; }
        public string YearStarted { get; set; }
        public string EmployeeGroupApprovals { get; set; }
        public string FutureUseIndicator { get; set; }
        public string Revenuerange { get; set; }
        public Nullable<decimal> SynchronizationStatus { get; set; }
        public Nullable<decimal> PreviousErrorStatus { get; set; }
        public Nullable<decimal> ServerStatus { get; set; }
    }
}
