//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIRequestDataKey
    {
        public APIRequestDataKey()
        {
            this.APIRequestData = new HashSet<APIRequestData>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> APIRequestDataKeyClassID { get; set; }
        public string Name { get; set; }
        public bool ValueRequired { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> APISFProductID { get; set; }
    
        public virtual ICollection<APIRequestData> APIRequestData { get; set; }
        public virtual APIRequestDataKeyClass APIRequestDataKeyClass { get; set; }
        public virtual APISFProduct APISFProduct { get; set; }
    }
}
