//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIRequest
    {
        public APIRequest()
        {
            this.APIRequestData = new HashSet<APIRequestData>();
        }
    
        public decimal ID { get; set; }
        public decimal APISourceID { get; set; }
        public decimal APIRequestSourceID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ICollection<APIRequestData> APIRequestData { get; set; }
        public virtual APIRequestSource APIRequestSource { get; set; }
        public virtual APISource APISource { get; set; }
    }
}
