//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class APISFProduct
    {
        public APISFProduct()
        {
            this.APIRequestDataKey = new HashSet<APIRequestDataKey>();
        }
    
        public decimal ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Order { get; set; }
    
        public virtual ICollection<APIRequestDataKey> APIRequestDataKey { get; set; }
    }
}
