//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class APISource
    {
        public APISource()
        {
            this.APIRequest = new HashSet<APIRequest>();
        }
    
        public decimal ID { get; set; }
        public string Token { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<APIRequest> APIRequest { get; set; }
    }
}
