//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public string Company { get; set; }
        public decimal ID { get; set; }
        public string UnitNumber { get; set; }
        public Nullable<decimal> ParentNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<decimal> SequenceNumber { get; set; }
        public string MajorAccountingClass { get; set; }
        public string EquipmentClass { get; set; }
        public string Manufacturer { get; set; }
        public string ModelYear { get; set; }
        public string TotalLength { get; set; }
        public string BusinessUnit { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string DescriptionCompressed { get; set; }
        public Nullable<int> DateAcquired { get; set; }
        public Nullable<int> DateDisposedorRetired { get; set; }
        public string EquipmentStatus { get; set; }
        public string NeworUsedonAcquisition { get; set; }
        public Nullable<decimal> AmountEstimatedSalvageValue { get; set; }
        public Nullable<decimal> AmountReplacementCost { get; set; }
        public Nullable<decimal> AmountLastYearsReplacementCost { get; set; }
        public string AssetCostAccountBusinessUnit { get; set; }
        public string AssetCostAccountObject { get; set; }
        public string AssetCostAccountSubsidiary { get; set; }
        public string AccumulatedDepreciationAccountBU { get; set; }
        public string AccumulatedDepreciationAccountObjct { get; set; }
        public string AccumulatedDepreciationAccountSub { get; set; }
        public string DepreciationExpenseBU { get; set; }
        public string DepreciationExpenseObject { get; set; }
        public string DepreciationExpenseSubsidiary { get; set; }
        public string AssetRevenueBusinessUnit { get; set; }
        public string AssetRevenueObject { get; set; }
        public string AssetRevenueSubsidiary { get; set; }
        public Nullable<decimal> AssetItemCurrentQuantity { get; set; }
        public Nullable<decimal> AssetItemOriginalQuantity { get; set; }
        public Nullable<decimal> TaxEntity { get; set; }
        public Nullable<decimal> AmountInvestmentTaxCredit { get; set; }
        public Nullable<decimal> AmountInvestmentTaxCreditPYE { get; set; }
        public string FinancingMethod { get; set; }
        public string ITCOwnedYN { get; set; }
        public string PurchaseOption { get; set; }
        public Nullable<decimal> AmountPurchaseOptionPrice { get; set; }
        public Nullable<decimal> PurchaseOptionCreditPercentage { get; set; }
        public Nullable<decimal> AmountPurchaseOptionMaximumCredit { get; set; }
        public Nullable<decimal> AddressNumberLessorRentorMortgagor { get; set; }
        public Nullable<int> DateContractDate { get; set; }
        public Nullable<int> DateExpiredJulian { get; set; }
        public Nullable<decimal> AmountMonthlyPayment { get; set; }
        public string NameRemark1 { get; set; }
        public string NameRemark2 { get; set; }
        public string InsurancePolicyNumber { get; set; }
        public string InsuranceCompany { get; set; }
        public Nullable<decimal> PolicyRenewalMonth { get; set; }
        public Nullable<decimal> AmountInsurancePremium { get; set; }
        public Nullable<decimal> AmountInsuranceValue { get; set; }
        public Nullable<decimal> InsuranceValueIndexfutureuse { get; set; }
        public string UserID { get; set; }
        public Nullable<int> DateLastChanged { get; set; }
        public string BusinessUnitLocation { get; set; }
        public string State { get; set; }
        public string ProgramID { get; set; }
        public Nullable<int> DateBeginningEffective { get; set; }
        public Nullable<int> DateExpectedReturn { get; set; }
        public string ActionMessageControl { get; set; }
        public string NameExplanation { get; set; }
        public string NameRemarkExplanation { get; set; }
        public Nullable<decimal> AddressNumber { get; set; }
        public string BoxWidth { get; set; }
        public string BoxLength { get; set; }
        public string CategoryCodeFA8 { get; set; }
        public string CategoryCodeFA9 { get; set; }
        public string CategoryCodeFA10RateGroup { get; set; }
        public Nullable<decimal> StandardFuelConsumption { get; set; }
        public string DisposalAccumulatedDepreciationBU { get; set; }
        public string DisposalAccumulatedDepreciationObj { get; set; }
        public string DisposalAccumulatedDepreciationSub { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> v { get; set; }
        public string Kit2ndItemNumber { get; set; }
        public string AFENumber { get; set; }
        public string JobTypeCraftCode { get; set; }
        public string JobStep { get; set; }
        public string UnionCode { get; set; }
        public string SubledgerInactiveCode { get; set; }
        public Nullable<int> DateUpdated { get; set; }
        public string WorkStationID { get; set; }
        public Nullable<decimal> TimeLastUpdated { get; set; }
        public string CategoryCodeFA20 { get; set; }
        public string CategoryCodeFA11 { get; set; }
        public string CategoryCodeFA12 { get; set; }
        public string CategoryCodeFA13 { get; set; }
        public string CategoryCodeFA14 { get; set; }
        public string CategoryCodeFA15 { get; set; }
        public string CategoryCodeFA16 { get; set; }
        public string CategoryCodeFA17 { get; set; }
        public string CategoryCodeFA18 { get; set; }
        public string CategoryCodeFA19 { get; set; }
        public string CategoryCodeFA21 { get; set; }
        public string CategoryCodeFA22 { get; set; }
        public string CategoryCodeFA23 { get; set; }
        public string AllowWorkOrderYN { get; set; }
        public Nullable<decimal> Criticality { get; set; }
        public string WarrantyFlag { get; set; }
        public Nullable<int> DateWarrantyExpirationJulian { get; set; }
    }
}
