//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUnit
    {
        public string ID { get; set; }
        public string BusinessUnitType { get; set; }
        public string DescriptionCompressed { get; set; }
        public string LevelofDetailBusinessUnit { get; set; }
        public string Company { get; set; }
        public Nullable<decimal> AddressNumber { get; set; }
        public Nullable<decimal> AddressNumberJobAR { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        public string ModelAccountsandConsolidationFlag { get; set; }
        public string Description { get; set; }
        public string Description02 { get; set; }
        public string Description03 { get; set; }
        public string Description04 { get; set; }
        public string Division { get; set; }
        public string CategoryCodeBusinessUnit02 { get; set; }
        public string Area { get; set; }
        public string Group { get; set; }
        public string BranchOffice { get; set; }
        public string CategoryCodeBusinessUnit06 { get; set; }
        public string LineofBusiness { get; set; }
        public string CategoryCodeBusinessUnit08 { get; set; }
        public string CategoryCodeBusinessUnit09 { get; set; }
        public string MajorProjectGroup { get; set; }
        public string CategoryCodeBusinessUnit11 { get; set; }
        public string CategoryCodeBusinessUnit12 { get; set; }
        public string CategoryCodeBusinessUnit13 { get; set; }
        public string CategoryCodeBusinessUnit14 { get; set; }
        public string CategoryCodeBusinessUnit15 { get; set; }
        public string CategoryCodeBusinessUnit16 { get; set; }
        public string MajorProjectType { get; set; }
        public string CompanyNumber { get; set; }
        public string DefaultCompanyNumber { get; set; }
        public string CategoryCodeBusinessUnit20 { get; set; }
        public string DivisionManager { get; set; }
        public string CategoryCodeBusinessUnit22 { get; set; }
        public string AreaManager { get; set; }
        public string GroupManager { get; set; }
        public string BranchManager { get; set; }
        public string CategoryCodeBusinessUnit26 { get; set; }
        public string CategoryCodeBusinessUnit27 { get; set; }
        public string CategoryCodeBusinessUnit28 { get; set; }
        public string CategoryCodeBusinessUnit29 { get; set; }
        public string CategoryCodeBusinessUnit30 { get; set; }
        public string TaxArea { get; set; }
        public Nullable<decimal> TaxEntity { get; set; }
        public string TaxRateArea { get; set; }
        public string TaxExplCode1 { get; set; }
        public string TaxDeductionCodes01 { get; set; }
        public string TaxDeductionCodes02 { get; set; }
        public string TaxDeductionCodes03 { get; set; }
        public string TaxDeductionCodes04 { get; set; }
        public string TaxDeductionCodes05 { get; set; }
        public string TaxDeductionCodes06 { get; set; }
        public string TaxDeductionCodes07 { get; set; }
        public string TaxDeductionCodes08 { get; set; }
        public string TaxDeductionCodes09 { get; set; }
        public string TaxDeductionCodes10 { get; set; }
        public string TaxDistributableNonDistrCode01 { get; set; }
        public string TaxDistributableNonDistrCode02 { get; set; }
        public string TaxDistributableNonDistrCode03 { get; set; }
        public string TaxDistributableNonDistrCode04 { get; set; }
        public string TaxDistributableNonDistrCode05 { get; set; }
        public string TaxDistributableNonDistrCode06 { get; set; }
        public string TaxDistributableNonDistrCode07 { get; set; }
        public string TaxDistributableNonDistrCode08 { get; set; }
        public string TaxDistributableNonDistrCode09 { get; set; }
        public string TaxDistributableNonDistrCode10 { get; set; }
        public string TaxorDeductionComputeStatusCode01 { get; set; }
        public string TaxorDeductionComputeStatusCode02 { get; set; }
        public string TaxorDeductionComputeStatusCode03 { get; set; }
        public string TaxorDeductionComputeStatusCode04 { get; set; }
        public string TaxorDeductionComputeStatusCode05 { get; set; }
        public string TaxorDeductionComputeStatusCode06 { get; set; }
        public string TaxorDeductionComputeStatusCode07 { get; set; }
        public string TaxorDeductionComputeStatusCode08 { get; set; }
        public string TaxorDeductionComputeStatusCode09 { get; set; }
        public string TaxorDeductionComputeStatusCode10 { get; set; }
        public string PostingEditBusinessUnit { get; set; }
        public string AllocationSummarizationMethod { get; set; }
        public string InvoiceStmtSummarizationMethod { get; set; }
        public string GLBankAccount { get; set; }
        public string AllocationLevel { get; set; }
        public string LaborDistributionMethod { get; set; }
        public Nullable<decimal> LaborDistributionMultiplier { get; set; }
        public string ObjectAccountLaborAccount { get; set; }
        public string ObjectAccountPremiumAccount { get; set; }
        public string ObjectAccountBurden { get; set; }
        public string SubsidiaryBurdenCostCode { get; set; }
        public Nullable<decimal> UnitsTotal { get; set; }
        public string SubledgerInactiveCode { get; set; }
        public Nullable<decimal> Supervisor { get; set; }
        public string ContractType { get; set; }
        public string CertifiedJob { get; set; }
        public string BusinessUnitSubsequent { get; set; }
        public string BillingTypeBusinessUnit { get; set; }
        public Nullable<decimal> PercentComplete { get; set; }
        public Nullable<decimal> PercentCompleteAggregateDetail { get; set; }
        public Nullable<decimal> AmountCosttoCompleteobsolete { get; set; }
        public string InterestComputationCodeAR { get; set; }
        public string InterestCompLateRevenue { get; set; }
        public Nullable<int> v { get; set; }
        public Nullable<int> DateActualStart { get; set; }
        public Nullable<int> DatePlannedComplete { get; set; }
        public Nullable<int> DateActualComplete { get; set; }
        public Nullable<int> DateOther5 { get; set; }
        public Nullable<int> DateOther6 { get; set; }
        public Nullable<int> DateFinalPaymentJulian { get; set; }
        public Nullable<decimal> AmountCostatCompletion { get; set; }
        public Nullable<decimal> AmountProfitatCompletion { get; set; }
        public string EqualEmploymentOpportunity { get; set; }
        public string EquipmentRateCode { get; set; }
        public string UserID { get; set; }
        public string ProgramID { get; set; }
        public Nullable<int> DateUpdated { get; set; }
        public string WorkStationID { get; set; }
        public Nullable<decimal> TimeLastUpdated { get; set; }
        public string BranchType { get; set; }
        public string APSBusinessUnit { get; set; }
        public string TargetBusinessUnit { get; set; }
    }
}
