//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomAsset
    {
        public decimal ID { get; set; }
        public Nullable<int> LicenseCODate { get; set; }
        public string LicenseCOLocation { get; set; }
        public string LicensePowerOfAttorny { get; set; }
        public Nullable<int> DateAction { get; set; }
        public string FeeCode { get; set; }
        public string Exempt { get; set; }
        public string UserTheJobWillBeLaunchedWith { get; set; }
        public Nullable<int> ScheduledStartDate { get; set; }
        public Nullable<int> ScheduledEndDate { get; set; }
        public string PromotionName { get; set; }
        public Nullable<decimal> QuoteNumber { get; set; }
        public Nullable<decimal> QuoteRevisionNumber { get; set; }
        public Nullable<decimal> OEBillingSeqSkey { get; set; }
        public Nullable<decimal> HoursWorked { get; set; }
        public string DDPScriptComments { get; set; }
        public string GenericStringx50 { get; set; }
        public Nullable<decimal> PurchaseAmount { get; set; }
        public Nullable<decimal> AmountGross { get; set; }
        public Nullable<decimal> AmountNet { get; set; }
        public Nullable<decimal> TotalBilledToDate { get; set; }
        public Nullable<decimal> AddressNumber { get; set; }
        public Nullable<decimal> CurrentPeriodDepreciation { get; set; }
        public Nullable<decimal> YTDDepreciation { get; set; }
        public Nullable<decimal> Amount1 { get; set; }
        public Nullable<decimal> Amount2 { get; set; }
        public Nullable<decimal> ExpenseAmount { get; set; }
        public Nullable<decimal> TotalDollars { get; set; }
        public Nullable<decimal> CostActual { get; set; }
        public Nullable<decimal> AmountBest { get; set; }
        public Nullable<decimal> AmountFinalforCost { get; set; }
        public Nullable<decimal> AmountTax1 { get; set; }
        public Nullable<decimal> AmountTax2 { get; set; }
        public Nullable<decimal> AmountListPrice { get; set; }
        public Nullable<decimal> TotalActualCost { get; set; }
        public Nullable<decimal> DepreciationFormulaAmount { get; set; }
        public Nullable<decimal> MathNumeric01 { get; set; }
        public Nullable<decimal> MathNumeric02 { get; set; }
        public Nullable<decimal> MathNumeric03 { get; set; }
        public Nullable<decimal> MathNumeric04 { get; set; }
        public Nullable<decimal> MathNumeric05 { get; set; }
        public string GenericString01 { get; set; }
        public Nullable<decimal> GenericNumeric1 { get; set; }
        public Nullable<decimal> GenericNumeric2 { get; set; }
        public Nullable<decimal> GenericNumeric3 { get; set; }
        public Nullable<decimal> GenericNumeric4 { get; set; }
        public Nullable<decimal> GenericNumeric5 { get; set; }
        public Nullable<decimal> GenericNumeric6 { get; set; }
        public Nullable<int> InServiceDate { get; set; }
        public Nullable<decimal> EquipmentCostAmount { get; set; }
        public string UpdatedByUser { get; set; }
        public Nullable<int> DateUpdated1 { get; set; }
        public Nullable<int> DateUpdated2 { get; set; }
        public Nullable<decimal> TimeLastUpdated { get; set; }
        public string ProgramID { get; set; }
        public string WorkStationID { get; set; }
        public string UserID { get; set; }
    }
}
