//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public decimal ID { get; set; }
        public string Country { get; set; }
        public string CompanyOwned { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> DocumentOrderNoInvoiceetc { get; set; }
        public string OrderType { get; set; }
        public string OrderCompanyOrderNumber { get; set; }
        public Nullable<decimal> LineNumber { get; set; }
        public Nullable<int> DateOrderedJulian { get; set; }
        public Nullable<int> DateShippedJulian { get; set; }
        public Nullable<int> DateActualShipDate { get; set; }
        public Nullable<decimal> AddressNumberShipTo { get; set; }
        public Nullable<decimal> AddressNumberParent { get; set; }
        public Nullable<decimal> Salesperson01 { get; set; }
        public Nullable<decimal> AddressNumberOwnerBilling { get; set; }
        public string RelatedPOSOWONumber { get; set; }
        public string RelatedPOSOWOOrderType { get; set; }
        public Nullable<int> DateCompletionJulian { get; set; }
        public Nullable<decimal> PrimaryLastSupplierNumber { get; set; }
        public string OriginalOrderNumber { get; set; }
        public string OriginalOrderType { get; set; }
        public string DocumentCompanyOriginalOrder { get; set; }
        public string OrderSuffix { get; set; }
        public Nullable<decimal> OriginalLineNumber { get; set; }
        public string ProductFamily { get; set; }
        public string ProductModel { get; set; }
        public string ProductComponent { get; set; }
        public string ConfiguredModel { get; set; }
        public string InstallKey { get; set; }
        public string VehicleIdentificatonNumber { get; set; }
        public string ReferenceNumber { get; set; }
        public string CategoryCodeEquipment01 { get; set; }
        public string CategoryCodeEquipment02 { get; set; }
        public string CategoryCodeEquipment03 { get; set; }
        public string CategoryCodeEquipment04 { get; set; }
        public string SquareFootage { get; set; }
        public string CategoryCodeEquipment06 { get; set; }
        public string CategoryCodeEquipment07 { get; set; }
        public string CategoryCodeEquipment08 { get; set; }
        public string CategoryCodeEquipment09 { get; set; }
        public string CategoryCodeEquipment10 { get; set; }
        public string UserReservedCode { get; set; }
        public Nullable<int> UserReservedDate { get; set; }
        public Nullable<decimal> UserReservedAmount { get; set; }
        public Nullable<decimal> UserReservedNumber { get; set; }
        public string UserReservedReference { get; set; }
        public string Createdbyuser { get; set; }
        public string UserID { get; set; }
        public string ProgramID { get; set; }
        public string WorkStationID { get; set; }
        public Nullable<int> DateUpdated { get; set; }
        public Nullable<decimal> TimeLastUpdated { get; set; }
        public string LotSerialNumber { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> WorkOrderNumber { get; set; }
        public string BillRevisionLevel { get; set; }
        public Nullable<int> EffectiveFromDate { get; set; }
        public Nullable<decimal> DefaultDealer { get; set; }
        public Nullable<decimal> AssessorNumber { get; set; }
        public string TermsAcceptedFlag { get; set; }
        public string SalesType { get; set; }
        public Nullable<int> InServiceDate { get; set; }
        public string BusinessUnit { get; set; }
        public string MeterReadingRequired { get; set; }
        public string RegistrationStatus { get; set; }
        public string ComponentCodeSystem { get; set; }
        public string ComponentCodeAssembly { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<decimal> Distributor { get; set; }
        public Nullable<decimal> EquipmentPartsNumber { get; set; }
    }
}
