//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetAttribute
    {
        public decimal ID { get; set; }
        public string SystemKey { get; set; }
        public string RT { get; set; }
        public string LookupKey { get; set; }
        public string Description { get; set; }
        public string EV01 { get; set; }
        public string UpdateUser { get; set; }
        public string UpdatePID { get; set; }
        public Nullable<int> UpdateDate { get; set; }
        public Nullable<decimal> UpdateTime { get; set; }
    }
}
