//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.InventoryProduct = new HashSet<InventoryProduct>();
        }
    
        public int ID { get; set; }
        public decimal LocationNumber { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public string CreatedByUser { get; set; }
        public string ModifiedByUser { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        public virtual ICollection<InventoryProduct> InventoryProduct { get; set; }
    }
}
