//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemBranch
    {
        public decimal ID { get; set; }
        public string SecondItemNumber { get; set; }
        public string ThirdItemNumber { get; set; }
        public string BusinessUnitID { get; set; }
        public string SalesCatalogSection { get; set; }
        public string SubSection { get; set; }
        public string SalesCategoryCode3 { get; set; }
        public string SalesCategoryCode4 { get; set; }
        public string Region { get; set; }
        public string CategoryCode6 { get; set; }
        public string CategoryCode7 { get; set; }
        public string CategoryCode8 { get; set; }
        public string CategoryCode9 { get; set; }
        public string CategoryCode10 { get; set; }
        public string CommodityClass { get; set; }
        public string CommoditySubClass { get; set; }
        public string SupplierRebateCode { get; set; }
        public string MasterPlanningFamily { get; set; }
        public string PurchasingCategoryCode5 { get; set; }
        public string GroupItemDimension { get; set; }
        public string GroupWarehouseProcess1 { get; set; }
        public string GroupWarehouseProcess2 { get; set; }
        public string GroupWarehouseProcess3 { get; set; }
        public string ItemPool { get; set; }
        public string CommodityCode { get; set; }
        public string ProductGroup { get; set; }
        public string DispatchGroup { get; set; }
        public Nullable<decimal> PrimaryLastSupplierNumber { get; set; }
        public Nullable<decimal> PlannerNumber { get; set; }
        public Nullable<decimal> BuyerNumber { get; set; }
        public string CategoryGL { get; set; }
        public string CountryofOrigin { get; set; }
        public Nullable<decimal> ReorderPointInput { get; set; }
        public Nullable<decimal> ReorderQuantityInput { get; set; }
        public Nullable<decimal> ReorderQuantityMaximum { get; set; }
        public Nullable<decimal> ReorderQuantityMinimum { get; set; }
        public Nullable<decimal> QuantityOrderMultiplesSOPO { get; set; }
        public Nullable<decimal> ServiceLevel { get; set; }
        public Nullable<decimal> SafetyStock { get; set; }
        public Nullable<decimal> DaysShelfLifeDays { get; set; }
        public string CheckAvailabilityYN { get; set; }
        public string LayerCodeSource { get; set; }
        public string LotStatusCode { get; set; }
        public string PotencyControl { get; set; }
        public string GradeControl { get; set; }
        public Nullable<decimal> StandardPotency { get; set; }
        public Nullable<decimal> FromPotency { get; set; }
        public Nullable<decimal> ThruPotency { get; set; }
        public string StandardGrade { get; set; }
        public string FromGrade { get; set; }
        public string ThruGrade { get; set; }
        public string ComponentType { get; set; }
        public Nullable<decimal> MarginMaintenance { get; set; }
        public string ItemPriceGroup { get; set; }
        public string RepriceBasketPriceCategory { get; set; }
        public string OrderRepriceCategory { get; set; }
        public string BackordersAllowedYN { get; set; }
        public string ItemFlashMessage { get; set; }
        public string ABCCode1SalesInventory { get; set; }
        public string ABCCode1MarginInventory { get; set; }
        public string ABCCode3InvestmentInventory { get; set; }
        public string ABCCodeOverrideIndicator { get; set; }
        public string ShippingCommodityClass { get; set; }
        public Nullable<decimal> CarrierNumber { get; set; }
        public Nullable<decimal> PreferredCarrierPurchasing { get; set; }
        public string ShippingConditionsCode { get; set; }
        public string StockingType { get; set; }
        public string LineType { get; set; }
        public string FIFOProcessing { get; set; }
        public string CycleCountCategory { get; set; }
        public string PrintMessage { get; set; }
        public string TypeWarranty { get; set; }
        public string SerialNumberRequired { get; set; }
        public Nullable<decimal> PercentMargin { get; set; }
        public string CommissionCategory { get; set; }
        public string AIADocumentFlag { get; set; }
        public string PurchasingTaxableYN { get; set; }
        public string SalesTaxableYN { get; set; }
        public string PlanningCode { get; set; }
        public string ItemDisplayCode { get; set; }
        public string FlagNetChange { get; set; }
        public Nullable<decimal> UnitsPerContainer { get; set; }
        public string RoundtoWholeNumber { get; set; }
        public string ItemRevisionLevel { get; set; }
        public Nullable<decimal> LeadtimeLevel { get; set; }
        public Nullable<decimal> LeadtimeMFG { get; set; }
        public Nullable<decimal> LeadtimeCumulative { get; set; }
        public string OrderPolicyCode { get; set; }
        public Nullable<decimal> ValueOrderPolicy { get; set; }
        public Nullable<decimal> QuantityAccountingCost { get; set; }
        public Nullable<decimal> QuantityMFGLeadtime { get; set; }
        public Nullable<decimal> LeadtimePerUnit { get; set; }
        public string PlanningTimeFenceRule { get; set; }
        public string FixedorVariableLeadtime { get; set; }
        public string IssueTypeCode { get; set; }
        public string ECONumber { get; set; }
        public string EngineeringChangeReason { get; set; }
        public Nullable<int> DateEngineeringChangeDate { get; set; }
        public Nullable<decimal> PlanningTimeFenceDays { get; set; }
        public Nullable<decimal> FreezeTimeFenceDays { get; set; }
        public Nullable<decimal> MessageTimeFenceDays { get; set; }
        public Nullable<decimal> MPSMRPTimeFence4 { get; set; }
        public Nullable<decimal> ShipmentLeadtimeOffset { get; set; }
        public Nullable<decimal> MoveHoursStandard { get; set; }
        public Nullable<decimal> QueueHoursStandard { get; set; }
        public Nullable<decimal> SetupLaborStandard { get; set; }
        public Nullable<decimal> ShrinkFactor { get; set; }
        public string ShrinkFactorMethod { get; set; }
        public string TimeBasisCode { get; set; }
        public Nullable<decimal> UnitsBatchQuantity { get; set; }
        public string OrderWith { get; set; }
        public Nullable<decimal> ExpediteDamperDays { get; set; }
        public Nullable<decimal> DeferDamperDays { get; set; }
        public Nullable<decimal> QuantityOrderMultiplesMRP { get; set; }
        public Nullable<decimal> SafetyLeadtime { get; set; }
        public string MakeBuyCode { get; set; }
        public Nullable<int> DateFutureUse { get; set; }
        public Nullable<decimal> LowLevelCode { get; set; }
        public string CommitmentMethod { get; set; }
        public string UserReservedCode { get; set; }
        public Nullable<int> UserReservedDate { get; set; }
        public Nullable<decimal> UserReservedAmount { get; set; }
        public Nullable<decimal> UserReservedNumber { get; set; }
        public string UserReservedReference { get; set; }
        public string UserID { get; set; }
        public string ProgramID { get; set; }
        public string WorkStationID { get; set; }
        public Nullable<int> DateUpdated { get; set; }
        public Nullable<decimal> TimeofDay { get; set; }
        public string StandardUnitofMeasureConversion { get; set; }
        public Nullable<decimal> CommitmentSpecificDays { get; set; }
        public Nullable<decimal> ReplenishmentHoursStandard { get; set; }
        public string IssueandReceipt { get; set; }
        public string ActiveIngredientFlag { get; set; }
        public Nullable<decimal> BestBeforeDefaultDays { get; set; }
        public string CommitmentDateMethod { get; set; }
        public string LotExpiratonDateCalculationMethod { get; set; }
        public Nullable<decimal> LotEffectiveDefaultDays { get; set; }
        public string MixDatesLotsYN { get; set; }
        public Nullable<decimal> PurchasingEffectiveDays { get; set; }
        public Nullable<decimal> SellByDefaultDays { get; set; }
        public Nullable<decimal> UserLotDate1DefaultDays { get; set; }
        public Nullable<decimal> UserLotDate2DefaultDays { get; set; }
        public Nullable<decimal> UserLotDate3DefaultDays { get; set; }
        public Nullable<decimal> UserLotDate4DefaultDays { get; set; }
        public Nullable<decimal> UserLotDate5DefaultDays { get; set; }
        public string CrossDockingFlag { get; set; }
        public string LotAuditFlag { get; set; }
        public string SpecialLotFormat { get; set; }
        public string RestrictWorkOrderLotAssignment { get; set; }
        public string LotNumberPreAssignment { get; set; }
        public string LotStatusCodeExpanded { get; set; }
        public string ConstraintsFlag { get; set; }
        public Nullable<decimal> PriorityOneAlertLevel { get; set; }
        public Nullable<decimal> PriorityTwoAlertLevel { get; set; }
        public Nullable<decimal> LeadtimeConversionFactor { get; set; }
        public string AllowShippingofHeldLots { get; set; }
        public Nullable<decimal> OperationalThreshold { get; set; }
        public Nullable<decimal> CumulativeThreshold { get; set; }
        public string ThresholdUnitofMeasure { get; set; }
        public string LeanManufacturingFlag { get; set; }
        public string LineCellIdentifier { get; set; }
        public Nullable<decimal> TotalProductCycleTime { get; set; }
        public string KanbanItem { get; set; }
        public string DemandFlowEndItemFlag { get; set; }
        public string KanbanExplodetoLowerLevel { get; set; }
        public string SellableItem { get; set; }
    }
}
