//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaborActivity
    {
        public string Region { get; set; }
        public string Branch { get; set; }
        public string BusinessUnit { get; set; }
        public string TypeOperationCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> EffectiveFromDate { get; set; }
        public Nullable<int> EffectiveThruDate { get; set; }
        public string CostComponent { get; set; }
        public string ActivityKey { get; set; }
        public Nullable<decimal> RunLaborStandard { get; set; }
        public Nullable<decimal> CrewSize { get; set; }
        public string UserReservedCode { get; set; }
        public Nullable<int> UserReservedDate { get; set; }
        public Nullable<decimal> UserReservedAmount { get; set; }
        public string UserReservedReference { get; set; }
        public Nullable<decimal> UserReservedNumber { get; set; }
        public string ProgramID { get; set; }
        public string WorkStationID { get; set; }
        public Nullable<int> DateUpdated { get; set; }
        public Nullable<decimal> TimeofDay { get; set; }
        public string UserID { get; set; }
    }
}
