//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public decimal ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Number { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> UpLevelID { get; set; }
        public decimal TypeID { get; set; }
        public decimal StatusID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<decimal> MainPhoneID { get; set; }
        public Nullable<decimal> FaxPhoneID { get; set; }
        public Nullable<decimal> System { get; set; }
        public string Description { get; set; }
        public string ManagerID { get; set; }
        public Nullable<decimal> ManagerOffsite { get; set; }
        public string ContantID { get; set; }
        public string EmployeeAdd { get; set; }
        public string EmployeeHide { get; set; }
        public Nullable<decimal> ReportInclude { get; set; }
        public Nullable<decimal> ReportOrder { get; set; }
        public Nullable<decimal> CompanyID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<decimal> LocationIDAddress { get; set; }
        public Nullable<decimal> LocationIDPhone { get; set; }
        public Nullable<decimal> LocationIDNet { get; set; }
        public Nullable<decimal> BranchLevel { get; set; }
        public Nullable<decimal> AreaLocationID { get; set; }
        public Nullable<decimal> RegionLocationID { get; set; }
        public Nullable<decimal> ReportLevel { get; set; }
        public string CountryID { get; set; }
        public Nullable<decimal> Lattitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string InternetFlag { get; set; }
        public string InternetDisplayName { get; set; }
    }
}
