//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWOFeithImage
    {
        public decimal ID { get; set; }
        public decimal WorkOrderID { get; set; }
        public string MWOImageID { get; set; }
        public string EmployeeNumber { get; set; }
        public string UnitNumber { get; set; }
        public string ComplexUnitNumber { get; set; }
        public string OMBOrderInbound { get; set; }
        public string Location { get; set; }
        public string Damaged { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string WorkOrderGUID { get; set; }
        public Nullable<decimal> ImageTypeID { get; set; }
    }
}
