//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMBFleetCategory
    {
        public string SystemCode { get; set; }
        public string ID { get; set; }
        public string Flag { get; set; }
        public Nullable<decimal> SortSequence { get; set; }
    }
}
