//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMBLookup
    {
        public decimal ID { get; set; }
        public Nullable<decimal> CategoryID { get; set; }
        public string MemberCode { get; set; }
        public string MemberDescription { get; set; }
        public Nullable<decimal> SortSequence { get; set; }
        public string MemberCategoryCode1 { get; set; }
        public string MemberCategoryCode2 { get; set; }
        public string MemberCategoryCode3 { get; set; }
        public string MemberCategoryCode4 { get; set; }
        public string SFDCReferenceID { get; set; }
    }
}
