//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMBOrderHeader
    {
        public OMBOrderHeader()
        {
            this.OMB_UNIT = new HashSet<OMBUnit>();
        }
    
        public decimal ID { get; set; }
        public decimal SequenceNumber { get; set; }
        public string SISOrderKey { get; set; }
        public Nullable<decimal> OrderTypeID { get; set; }
        public decimal QStatusID { get; set; }
        public Nullable<decimal> BillGroupSKey { get; set; }
        public string OECompany { get; set; }
        public string OELocation { get; set; }
        public string TMPBillPhone { get; set; }
        public string TMPBillAddress1 { get; set; }
        public string TMPBillAddress2 { get; set; }
        public string TMPBillAddress3 { get; set; }
        public string TMPBillCity { get; set; }
        public string TMPBillState { get; set; }
        public string TMPBillZip { get; set; }
        public string TMPBillCountry { get; set; }
        public Nullable<decimal> SiteContactIDLN { get; set; }
        public Nullable<decimal> AddressBookID { get; set; }
        public string SICCode { get; set; }
        public Nullable<decimal> SourceSKey { get; set; }
        public Nullable<decimal> PurchasingAgentIDLN { get; set; }
        public string RevenueLocation { get; set; }
        public string BillInAreaRS { get; set; }
        public string InvoiceInAdvance { get; set; }
        public Nullable<System.DateTime> QDateTime { get; set; }
        public Nullable<decimal> ThirdPartyID { get; set; }
        public Nullable<decimal> DealerID { get; set; }
        public Nullable<System.DateTime> BillThruDate { get; set; }
        public string JDEMPJobNumber { get; set; }
        public string CreditCardNumber { get; set; }
        public string CreditCardExpirationDate { get; set; }
        public string ExemptLicenseFeeFlag { get; set; }
        public Nullable<decimal> WSQuoteNumber { get; set; }
        public Nullable<decimal> WSQuoteRevisionNumber { get; set; }
        public string ExemptRRIFlag { get; set; }
        public string Certificate { get; set; }
        public Nullable<System.DateTime> FreeMonth { get; set; }
        public Nullable<decimal> BillDay { get; set; }
        public string BondNumber { get; set; }
        public Nullable<decimal> BondAmount { get; set; }
        public string NationalAccountJobNumber { get; set; }
        public string DeliveryDirections { get; set; }
        public string SiteWorkMaterials { get; set; }
        public string ACQCode { get; set; }
        public Nullable<decimal> NumberOfInvoices { get; set; }
        public string CancelReasonDescription { get; set; }
        public Nullable<decimal> MarketingUseID { get; set; }
        public string CreditStatus { get; set; }
        public Nullable<decimal> CreditStatusReasonID { get; set; }
        public string CreditUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreditUpdatedDate { get; set; }
        public string BranchComment { get; set; }
        public string CreditComment { get; set; }
        public string ArticlesOfIncFlag { get; set; }
        public string LetterOfGoodStandingFlag { get; set; }
        public string CreditRequirementsFlag { get; set; }
        public Nullable<System.DateTime> CreditRequestDate { get; set; }
        public string InitialChargesFlag { get; set; }
        public string FinalChargesFlag { get; set; }
        public string EntireContractFlag { get; set; }
        public string LastMonthFlag { get; set; }
        public Nullable<decimal> NumberOfMonthsUpFront { get; set; }
        public string InitialInvoiceCODFlag { get; set; }
        public Nullable<decimal> SalesPercentDown { get; set; }
        public Nullable<decimal> SalesPercentPreDelivery { get; set; }
        public Nullable<decimal> SalesPercentNet { get; set; }
        public Nullable<decimal> SalesPercentNetDays { get; set; }
        public Nullable<decimal> CostPerSqaureFoot { get; set; }
        public Nullable<decimal> ExemptPPTID { get; set; }
        public string ExemptPPTUserID { get; set; }
        public string TaxNotes { get; set; }
        public Nullable<decimal> PPTRate { get; set; }
        public Nullable<decimal> AffiliateProgramID { get; set; }
        public string BranchRRIEExemptFlag { get; set; }
        public string BranchRRIEExemptUser { get; set; }
        public string BillNotes { get; set; }
        public string SpecialNotes { get; set; }
        public Nullable<decimal> InvoiceHandleID { get; set; }
        public string SpecialProjectFlag { get; set; }
        public string ModularBuildingFlag { get; set; }
        public Nullable<decimal> BillIdln { get; set; }
        public Nullable<decimal> BillRCK7 { get; set; }
        public Nullable<decimal> SiteContactRCK7 { get; set; }
        public Nullable<decimal> PurchasingAgentRCK7 { get; set; }
        public string EOYExclusion { get; set; }
        public Nullable<System.DateTime> BranchRRIEExemptDate { get; set; }
        public Nullable<decimal> UseCreditCardID { get; set; }
        public Nullable<decimal> TaxFrequencyID { get; set; }
        public Nullable<decimal> Ship_Idln { get; set; }
        public Nullable<decimal> ShipRck7 { get; set; }
        public Nullable<decimal> WSMktPromRef { get; set; }
        public string SFAUpdatesCompleteFlag { get; set; }
        public Nullable<System.DateTime> InsuranceRequestedDate { get; set; }
        public Nullable<decimal> LeaseAgreementID { get; set; }
        public Nullable<decimal> RequestInsuranceCertificateID { get; set; }
        public Nullable<decimal> UCC1FilingID { get; set; }
        public Nullable<decimal> AdvanceBillID { get; set; }
        public Nullable<decimal> PurchaseOptionID { get; set; }
        public string BypassDocumentFlag { get; set; }
        public string ContractNote { get; set; }
        public string EditValidationFlag { get; set; }
        public string FinalPackageFlag { get; set; }
        public string FederalID { get; set; }
        public string MaintenanceUserID { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public string CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] CreditCardCrypt { get; set; }
        public string CreditCardSuffix { get; set; }
        public Nullable<decimal> WSBusSectorRef { get; set; }
        public Nullable<decimal> WSPurchaseAgreement { get; set; }
        public Nullable<decimal> ProjectNumber { get; set; }
        public Nullable<decimal> ACHAccountSuffix { get; set; }
        public Nullable<decimal> CCEnrID { get; set; }
        public Nullable<decimal> CCGroupID { get; set; }
        public string OriginalRevenueLocation { get; set; }
        public string DeliveryRevenueLocation { get; set; }
        public Nullable<System.DateTime> InitialBillDate { get; set; }
        public string DeliverModelCode { get; set; }
        public Nullable<decimal> DeliveryUnitCount { get; set; }
        public string InsuranceNote { get; set; }
        public Nullable<decimal> CybersourceSubscriptionID { get; set; }
        public Nullable<decimal> AttentionToIdln { get; set; }
        public string SFDCOpportunityID { get; set; }
        public string SFDCQuoteID { get; set; }
        public string SFDCPrimaryQuoteProdID { get; set; }
        public string NAICSCode { get; set; }
        public string OriginatingSystem { get; set; }
        public string TMPBillAttention { get; set; }
        public Nullable<decimal> Mileage { get; set; }
        public string BMQuoteNumber { get; set; }
        public string PreparedBy { get; set; }
        public string BMSeqenceNumber { get; set; }
        public Nullable<System.DateTime> InitialBillGLDate { get; set; }
        public string SubleasedItems { get; set; }
        public string BMQuoteProdID { get; set; }
        public string GSAFlag { get; set; }
        public Nullable<System.DateTime> DeliverDateAtBilling { get; set; }
        public string CCSubscription { get; set; }
        public Nullable<System.DateTime> FinalBillDate { get; set; }
    
        public virtual ICollection<OMBUnit> OMB_UNIT { get; set; }
    }
}
