//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMBUnit
    {
        public decimal OMBOrderHeaderID { get; set; }
        public decimal ItemID { get; set; }
        public Nullable<decimal> AssetID { get; set; }
        public string NewUsedFlag { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> MinLease { get; set; }
        public Nullable<decimal> ActLease { get; set; }
        public Nullable<decimal> LeasePurchaseAmount { get; set; }
        public Nullable<decimal> ReplacementValue { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public string ReturnBranch { get; set; }
        public string Carrier { get; set; }
        public Nullable<System.DateTime> TransportEffDate { get; set; }
        public Nullable<System.DateTime> TransportExpDate { get; set; }
        public string RRICode { get; set; }
        public Nullable<decimal> RentRecapPercent { get; set; }
        public Nullable<decimal> UnitStatusID { get; set; }
        public string UnitNumber { get; set; }
        public string TmpModelType { get; set; }
        public string TmpModelWidth { get; set; }
        public string TmpModelLength { get; set; }
        public string TmpModelDescription { get; set; }
        public string TmpBoxLength { get; set; }
        public string TmpUnitCount { get; set; }
        public Nullable<decimal> ThirdPartyVendorAN8 { get; set; }
        public Nullable<decimal> PurchaseOptionStatusID { get; set; }
        public string CommissionOverrideFlag { get; set; }
        public string CommissionOverrideRequestor { get; set; }
        public string CommissionOverrideReason { get; set; }
        public Nullable<System.DateTime> CommissionOverrideDate { get; set; }
        public string OffRentQUser { get; set; }
        public string OffRentAddUser { get; set; }
        public string OffRentCHGUser { get; set; }
        public Nullable<System.DateTime> OffRentAddDate { get; set; }
        public Nullable<System.DateTime> OffRentCHGDate { get; set; }
        public Nullable<decimal> OffRentQStatusID { get; set; }
        public Nullable<System.DateTime> OffRentQDate { get; set; }
        public string OffRentRequestContact { get; set; }
        public string OffRentRequestPhone { get; set; }
        public Nullable<System.DateTime> OffRentRequestRECDDate { get; set; }
        public Nullable<System.DateTime> OffRentRequestPickupDate { get; set; }
        public Nullable<System.DateTime> OffRentScheduledPickupDate { get; set; }
        public Nullable<System.DateTime> OffRentActualPickupDate { get; set; }
        public string OffRentNote { get; set; }
        public string OnSiteTakeoverFlag { get; set; }
        public string EarleyTermReason { get; set; }
        public string MakeAvailableFlag { get; set; }
        public Nullable<System.DateTime> BillThruDate { get; set; }
        public string PickupBranch { get; set; }
        public string VendorPickup { get; set; }
        public string OffRentInstruction { get; set; }
        public string InsuranceMessageCode { get; set; }
        public Nullable<System.DateTime> LastRRIDate { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public string MaintenanceUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserID { get; set; }
        public string UnitNotes { get; set; }
        public Nullable<decimal> EarlyTermReasonID { get; set; }
        public Nullable<decimal> OffRentUnbilledAmount { get; set; }
        public Nullable<decimal> OffRentMinSettleAmount { get; set; }
        public Nullable<decimal> OffRentACTSettleAmount { get; set; }
        public Nullable<decimal> OffRentUndepTimaAmount { get; set; }
        public Nullable<System.DateTime> OffRentSuspendDate { get; set; }
        public Nullable<System.DateTime> OffRentDefaulBTDate { get; set; }
        public string OffRentInvInstruction { get; set; }
        public string Relocation { get; set; }
        public string RelocationChargeUser { get; set; }
        public Nullable<System.DateTime> RelocationChargeDate { get; set; }
        public string OffRentConfUser { get; set; }
        public Nullable<System.DateTime> OffRentConfDate { get; set; }
        public string OffRentConfMethod { get; set; }
        public string OffRentConfEmail { get; set; }
        public string OffRentConfFax { get; set; }
        public string OffRentConfFaxMessage { get; set; }
        public string OffRentConfSiteType { get; set; }
        public string OffRentConfSiteHours { get; set; }
        public string OffRentConfKnockdown { get; set; }
        public string OffRentConfFreight { get; set; }
        public string OffRentConfInstructions { get; set; }
        public string DeliveryConfirmation { get; set; }
        public Nullable<System.DateTime> DeliveryConfirmationDate { get; set; }
        public string DeliveryConfirmationNotes { get; set; }
        public Nullable<System.DateTime> OffRentMTBillThruDate { get; set; }
        public Nullable<System.DateTime> OffRentMTInvFromDate { get; set; }
        public Nullable<System.DateTime> OffRentMTInvThruDate { get; set; }
        public string OrigTmpModelType { get; set; }
        public string OrigModelCode { get; set; }
        public string OrigUnitCount { get; set; }
        public string PreOrCaller { get; set; }
        public string PreOrCallerPhone { get; set; }
        public string PreOrContact { get; set; }
        public string PreOrContactEmail { get; set; }
        public string PreOrContactPhone { get; set; }
        public string PreOrContactFax { get; set; }
        public Nullable<System.DateTime> PreOrRequestedPU { get; set; }
        public string PreOrComments { get; set; }
        public string QuotedLength { get; set; }
        public string QuotedWidth { get; set; }
        public string QuotedModel { get; set; }
        public string QuotedNewUsed { get; set; }
        public Nullable<System.DateTime> PhysicalDeliveryDate { get; set; }
        public string TmpStories { get; set; }
    
        public virtual OMBOrderHeader OMB_ORDER_HEADER { get; set; }
    }
}
