//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMBWorkOrder
    {
        public decimal WorkOrderID { get; set; }
        public string OrderType { get; set; }
        public string OMBOrderInbound { get; set; }
        public Nullable<decimal> OMBOrderOutbound { get; set; }
        public string Urcd { get; set; }
        public Nullable<int> Urdt { get; set; }
        public Nullable<decimal> Urat { get; set; }
        public string Urrf { get; set; }
        public Nullable<decimal> Ukurab { get; set; }
        public string ID { get; set; }
        public string JobNumber { get; set; }
        public Nullable<int> UpdateDate { get; set; }
        public Nullable<decimal> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<decimal> CustomerNumber { get; set; }
        public string AdditionalWork { get; set; }
    }
}
