//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.InventoryProduct = new HashSet<InventoryProduct>();
        }
    
        public int ID { get; set; }
        public int ProductCategoryID { get; set; }
        public int StatusID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CreatedByUser { get; set; }
        public string ModifiedByUser { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        public virtual ICollection<InventoryProduct> InventoryProduct { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductStatus ProductStatus { get; set; }
    }
}
