//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutingExtension
    {
        public decimal WorkOrderID { get; set; }
        public decimal SequenceNumberOperation { get; set; }
        public string TypeOperationCode { get; set; }
        public string BusinessUnit { get; set; }
        public string PayableYN { get; set; }
        public string BillableYN { get; set; }
        public Nullable<decimal> ActualBillableRate { get; set; }
        public Nullable<decimal> ActualPayableRate { get; set; }
        public Nullable<decimal> EstimatedAmount { get; set; }
        public Nullable<decimal> AmountActual { get; set; }
        public Nullable<decimal> AmountEstimated { get; set; }
        public Nullable<decimal> EstimatedBillableRate { get; set; }
        public Nullable<decimal> EstimatedPayableRate { get; set; }
        public Nullable<decimal> EstimatedPaymentAmount { get; set; }
        public Nullable<decimal> TotalBilled { get; set; }
        public Nullable<decimal> ClaimAmount { get; set; }
        public Nullable<int> DateBilled { get; set; }
        public Nullable<int> DatePaid { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> RateLaborPerHour { get; set; }
        public Nullable<int> DateActualStart { get; set; }
        public Nullable<decimal> TimeStartHHMMSS { get; set; }
        public Nullable<decimal> EstimateTimeEndingHHMMSS { get; set; }
        public string CostComponent { get; set; }
        public string EntitlementCheck { get; set; }
        public string CategoryGLNonCovered { get; set; }
        public string CategoryGLCovered { get; set; }
        public string UserID { get; set; }
        public string ProgramID { get; set; }
        public string WorkStationID { get; set; }
        public Nullable<int> DateUpdated { get; set; }
        public Nullable<decimal> TimeofDay { get; set; }
        public string PriceandAdjustmentScheduleFour { get; set; }
        public string PriceandAdjustmentScheduleService { get; set; }
        public Nullable<decimal> PercentCovered { get; set; }
        public string MethodofPricing { get; set; }
        public Nullable<decimal> ServiceAddressNumber { get; set; }
        public string ProductFamily { get; set; }
        public string ProductModel { get; set; }
        public string CoverageGroup { get; set; }
        public string PayPricingMethod { get; set; }
        public string PayServiceProviderforParts { get; set; }
        public string CurrencyCodeTo { get; set; }
        public string BillableCurrency { get; set; }
        public Nullable<decimal> BillableExchangeRate { get; set; }
        public string BillableCurrencyMode { get; set; }
        public Nullable<decimal> ForeignEstimatedBillableUnitRate { get; set; }
        public Nullable<decimal> ForeignEstimatedBillableAmount { get; set; }
        public Nullable<decimal> ForeignActualBillableUnitRate { get; set; }
        public Nullable<decimal> ForeignActualBillableAmount { get; set; }
        public string PayableCurrency { get; set; }
        public Nullable<decimal> PayableExchangeRate { get; set; }
        public string PayableCurrencyMode { get; set; }
        public Nullable<decimal> ForeignEstimatedPayableUnitRate { get; set; }
        public Nullable<decimal> ForeignEstimatedPayableAmount { get; set; }
        public Nullable<decimal> ForeignActualPayableUnitRate { get; set; }
        public Nullable<decimal> ForeignActualPayableAmount { get; set; }
        public Nullable<int> DateSubmitted { get; set; }
        public Nullable<decimal> TimeSubmitted { get; set; }
        public Nullable<decimal> CausalPart { get; set; }
        public string InvoiceRequired { get; set; }
        public string InvoiceReceived { get; set; }
        public string ComponentCodeAssembly { get; set; }
        public string CausalPartBusinessUnit { get; set; }
        public string SupplierLotNumber { get; set; }
        public Nullable<decimal> SupplierRecoveryVendorNumber { get; set; }
        public Nullable<decimal> UniqueKeyPricing { get; set; }
        public string DefectCode { get; set; }
        public string ComponentCodeSystem { get; set; }
        public string ComponentCodePart { get; set; }
        public string SourceforLaborLine { get; set; }
    }
}
