//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityLevel
    {
        public SecurityLevel()
        {
            this.Security = new HashSet<Security>();
        }
    
        public decimal ApplicationID { get; set; }
        public decimal LevelID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> SubApplicationID { get; set; }
        public decimal ID { get; set; }
    
        public virtual ICollection<Security> Security { get; set; }
    }
}
