//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public string Password { get; set; }
        public Nullable<int> SecurityLevelLevelID { get; set; }
        public decimal ActiveSession { get; set; }
        public string ChangeFlag { get; set; }
        public Nullable<decimal> ApplicationID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public string CreateID { get; set; }
        public string MaintenanceID { get; set; }
        public decimal SecurityLevelID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual SecurityLevel SecurityLevel { get; set; }
    }
}
