//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDefinedCode
    {
        public string ProductCode { get; set; }
        public string UserDefinedCodeTypeID { get; set; }
        public string UserDefinedCodeID { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string SpecialHandlingCodeUserDefCodes { get; set; }
        public string OwnershipFlagUserDefinedCodes { get; set; }
        public string HardCodedYN { get; set; }
        public string UserID { get; set; }
        public string ProgramID { get; set; }
        public Nullable<int> DateUpdated { get; set; }
        public string WorkStationID { get; set; }
        public Nullable<decimal> TimeLastUpdated { get; set; }
    }
}
