//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDefinedCodeType
    {
        public string ProductCode { get; set; }
        public string UserDefinedCodeTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> UserDefinedCodeSequenceNumber { get; set; }
        public string UserDefinedCodeClassCode1 { get; set; }
        public Nullable<decimal> CodeLength { get; set; }
        public string Line2DesiredYN { get; set; }
        public string NumericYN { get; set; }
        public string EnterpriseOneMergeControl { get; set; }
        public string MergeType { get; set; }
        public string UserID { get; set; }
        public string ProgramID { get; set; }
        public Nullable<int> DateUpdated { get; set; }
        public string WorkStationID { get; set; }
        public Nullable<decimal> TimeLastUpdated { get; set; }
    }
}
