//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderMasterTag
    {
        public decimal WorkOrderID { get; set; }
        public string LineCellIdentifier { get; set; }
        public string MonthWeekDayShift { get; set; }
        public Nullable<decimal> ScheduleSpread { get; set; }
        public string ShiftCode { get; set; }
        public string Serializedcomponents { get; set; }
        public string CostMethod { get; set; }
        public Nullable<decimal> AmountUnaccountedDirectLabor { get; set; }
        public Nullable<decimal> AmountUnaccountedScrap { get; set; }
        public Nullable<decimal> UnitsUnaccountedScrap { get; set; }
        public string AccountID { get; set; }
        public string AlertSensitiveTask { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> DateActualStartJulian { get; set; }
        public Nullable<decimal> SequenceBubbleSequence { get; set; }
        public string ChargeCosttoProjectAccount { get; set; }
        public string CurrencyCodeFrom { get; set; }
        public string CurrencyCodeSource { get; set; }
        public string CurrencyCodeOrigin { get; set; }
        public Nullable<int> DateOther5 { get; set; }
        public Nullable<int> DateOther6 { get; set; }
        public string DrawingNumber { get; set; }
        public string DualUnitOfMeasureItem { get; set; }
        public string ProductionCostsExist { get; set; }
        public string ChangestoPartsAndRoutingsAllowed { get; set; }
        public string ObjectAccount { get; set; }
        public Nullable<decimal> AmountActualOther { get; set; }
        public Nullable<decimal> ProjectNumber { get; set; }
        public string DirectProjectRelationship { get; set; }
        public string ShipThisPhase { get; set; }
        public Nullable<decimal> UnitsSecondaryQuantityOrdered { get; set; }
        public string ShrinkFactorMethod { get; set; }
        public Nullable<decimal> ShrinkFactor { get; set; }
        public Nullable<decimal> SecondaryQuantityCompleted { get; set; }
        public string ResourcesAssigned { get; set; }
        public string UnitofMeasureSecondary { get; set; }
        public string CategoriesWorkOrder11 { get; set; }
        public string CategoriesWorkOrder12 { get; set; }
        public string CategoriesWorkOrder13 { get; set; }
        public string CategoriesWorkOrder14 { get; set; }
        public string CategoriesWorkOrder15 { get; set; }
        public string CategoriesWorkOrder16 { get; set; }
        public string CategoriesWorkOrder17 { get; set; }
        public string CategoriesWorkOrder18 { get; set; }
        public string CategoriesWorkOrder19 { get; set; }
        public string CategoriesWorkOrder20 { get; set; }
        public string JobTypeCraftCode { get; set; }
        public string FirmWorkOrder { get; set; }
        public string PromotionID { get; set; }
        public string ProblemDescription { get; set; }
        public string ProductModel { get; set; }
        public string ContactName2 { get; set; }
        public string PhonePrefix { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<decimal> TimeCompleted { get; set; }
        public string MethodofPricing { get; set; }
        public string EntitlementCheck { get; set; }
        public string PaymentInstrument { get; set; }
        public Nullable<decimal> TimeGuaranteedResponse { get; set; }
        public string Country { get; set; }
        public string GeographicRegionCode { get; set; }
        public string TaxRateArea { get; set; }
        public string TaxExplCode1 { get; set; }
        public string Language { get; set; }
        public string CategoryGLCovered { get; set; }
        public string CategoryGLNonCovered { get; set; }
        public string CoverageGroup { get; set; }
        public string PriceandAdjustmentScheduleFour { get; set; }
        public string PriceandAdjustmentScheduleService { get; set; }
        public Nullable<decimal> TimeScheduledStartHHMMSS { get; set; }
        public Nullable<decimal> TimeScheduledEndHHMMSS { get; set; }
        public string DaylightSavingsRuleName { get; set; }
        public string TimeZoneList { get; set; }
        public string ProductFamily { get; set; }
        public Nullable<decimal> CausalPart { get; set; }
        public string CausalPartBusinessUnit { get; set; }
        public string SupplierLotNumber { get; set; }
        public string DefectCode { get; set; }
        public Nullable<int> FailureDate { get; set; }
        public Nullable<decimal> FailureTime { get; set; }
        public Nullable<int> RepairDate { get; set; }
        public Nullable<decimal> RepairTime { get; set; }
        public Nullable<decimal> PrimaryLastSupplierNumber { get; set; }
        public Nullable<decimal> AssessorNumber { get; set; }
        public Nullable<decimal> SupplierRecoveryManagerNumber { get; set; }
        public string EligibleSupplierRecovery { get; set; }
        public string EntitlementCheckSupplier { get; set; }
        public Nullable<decimal> CurrentBalanceofMeter1 { get; set; }
        public Nullable<decimal> CurrentBalanceofMeter2 { get; set; }
        public Nullable<decimal> CurrentBalanceofMeter3 { get; set; }
        public string CurrencyCodeTo { get; set; }
        public string CurrencyModeForeignorDomesticEntry { get; set; }
        public Nullable<decimal> CurrencyConversionRateSpotRate { get; set; }
        public string ComponentCodeSystem { get; set; }
        public string ComponentCodeAssembly { get; set; }
        public Nullable<decimal> SequenceNumber { get; set; }
        public Nullable<decimal> PlannedMaterial { get; set; }
        public Nullable<decimal> PlannedLabor { get; set; }
        public Nullable<decimal> PlannedOther { get; set; }
        public Nullable<decimal> BudgetedCost { get; set; }
        public Nullable<decimal> TotalEstimated { get; set; }
        public Nullable<decimal> TotalPlanned { get; set; }
        public Nullable<decimal> PlannedSpecialAmount { get; set; }
        public Nullable<decimal> PlannedSpecialUnits { get; set; }
        public Nullable<decimal> EstimatedSpecialAmount { get; set; }
        public Nullable<decimal> EstimatedSpecialUnits { get; set; }
        public Nullable<decimal> ActualSpecialAmount { get; set; }
        public Nullable<decimal> ActualSpecialUnits { get; set; }
        public Nullable<decimal> AmountCommittedOriginal { get; set; }
        public Nullable<decimal> AmountCommittedRemaining { get; set; }
        public string HeldPartsListFlag { get; set; }
        public string ComponentCodePart { get; set; }
        public string CallBacks { get; set; }
        public Nullable<decimal> IssueNumber { get; set; }
        public string ReimbursementMethod { get; set; }
        public Nullable<decimal> DocumentNumber { get; set; }
        public string DocumentType { get; set; }
        public string DocumentCompany { get; set; }
        public string ContractChangeNumber { get; set; }
        public Nullable<decimal> LineNumber { get; set; }
        public string CreatedByUser { get; set; }
        public string ExternalEventFlag { get; set; }
        public string LeadCraft { get; set; }
        public string MaintenanceScheduleFlag { get; set; }
    }
}
