//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderInstruction
    {
        public decimal WorkOrderID { get; set; }
        public string OrderType { get; set; }
        public string OrderSuffix { get; set; }
        public string RecordType { get; set; }
        public decimal WorkOrderLineNumber { get; set; }
        public Nullable<int> DateAssociatedSar { get; set; }
        public string DescriptionWorkOrder { get; set; }
        public string AssociatedWOItem1 { get; set; }
        public string AssociatedWOItem2 { get; set; }
        public string AssociatedWOItem3 { get; set; }
    }
}
