//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderActivity
    {
        public decimal WorkOrderID { get; set; }
        public string OrderType { get; set; }
        public string OrderSuffix { get; set; }
        public string TypeofRouting { get; set; }
        public Nullable<decimal> ParentshortItemNumber { get; set; }
        public string Kit2ndItemNumber { get; set; }
        public string ThirdItemNumberKit { get; set; }
        public string Branch { get; set; }
        public string LineCellIdentifier { get; set; }
        public string BusinessUnit { get; set; }
        public string AutoLoadDescription { get; set; }
        public string Description { get; set; }
        public decimal SequenceNumberOperations { get; set; }
        public string TypeOperationCode { get; set; }
        public string OperationStatusCodeWO { get; set; }
        public string InspectionCode { get; set; }
        public string TimeBasisCode { get; set; }
        public string LabororMachine { get; set; }
        public string PayPointCode { get; set; }
        public string PayPointStatus { get; set; }
        public string JobTypeCraftCode { get; set; }
        public Nullable<decimal> AddressNumber { get; set; }
        public Nullable<decimal> CriticalRatio { get; set; }
        public Nullable<decimal> SlackTimeRatio { get; set; }
        public Nullable<int> DateOrderTransaction { get; set; }
        public Nullable<int> DateRequested { get; set; }
        public Nullable<int> DateStartJulian { get; set; }
        public Nullable<int> DateCompletionJulian { get; set; }
        public string ShiftCodeRequested { get; set; }
        public string ShiftCodeStart { get; set; }
        public string ShiftCodeCompleted { get; set; }
        public Nullable<decimal> PercentLeadtimeOverlap { get; set; }
        public Nullable<decimal> PercentOverlap { get; set; }
        public Nullable<decimal> PercentOperationalPlannedYield { get; set; }
        public Nullable<decimal> PercentCumulativePlannedYield { get; set; }
        public Nullable<decimal> SequenceNumberNextOperation { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> MoveHoursStandard { get; set; }
        public Nullable<decimal> QueueHoursStandard { get; set; }
        public Nullable<decimal> RunMachineStandard { get; set; }
        public Nullable<decimal> ActivityHours { get; set; }
        public Nullable<decimal> SetupLaborStandard { get; set; }
        public Nullable<decimal> RunMachineActual { get; set; }
        public Nullable<decimal> RunLaborActual { get; set; }
        public Nullable<decimal> HoursSetupLaborHoursActual { get; set; }
        public Nullable<decimal> FactorOperationShrinkageFactor { get; set; }
        public Nullable<decimal> UnitsOrderTransactionQuantity { get; set; }
        public Nullable<decimal> UnitsQuantityCanceledScrapped { get; set; }
        public Nullable<decimal> QuantityShipped { get; set; }
        public Nullable<decimal> UnitsQuantityatOperation { get; set; }
        public Nullable<decimal> RatePiecework { get; set; }
        public string UnitofMeasureasInput { get; set; }
        public Nullable<decimal> HoursUnaccountedSetupLabor { get; set; }
        public Nullable<decimal> HoursUnaccountedMachineHours { get; set; }
        public Nullable<decimal> AmountUnaccountedDirectLabor { get; set; }
        public Nullable<decimal> AmountUnaccountedSetupLabor { get; set; }
        public Nullable<decimal> AmountUnaccountedMachine { get; set; }
        public string UnitorTagNumber { get; set; }
        public string MessageNumber { get; set; }
        public string ProjectBusinessUnit { get; set; }
        public string ObjectAccount { get; set; }
        public string Subsidiary { get; set; }
        public Nullable<decimal> PrimaryLastSupplierNumber { get; set; }
        public string CompanyKeyRelatedOrder { get; set; }
        public string RelatedPOSOWONumber { get; set; }
        public string RelatedPOSOWOOrderType { get; set; }
        public Nullable<decimal> RelatedPOSOLineNumber { get; set; }
        public string DocumentType { get; set; }
        public string UserReservedCode { get; set; }
        public Nullable<int> UserReservedDate { get; set; }
        public Nullable<decimal> UserReservedAmount { get; set; }
        public string UserReservedReference { get; set; }
        public Nullable<decimal> UserReservedNumber { get; set; }
        public string UserID { get; set; }
        public string ProgramID { get; set; }
        public string WorkStationID { get; set; }
        public Nullable<int> DateUpdated { get; set; }
        public Nullable<decimal> TimeofDay { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> ResourceUnitsConsumed { get; set; }
        public string CapacityUnitofmeasure { get; set; }
        public string WorkcenterBranch { get; set; }
        public Nullable<decimal> RunMachineCurrent { get; set; }
        public Nullable<decimal> RunLaborCurrent { get; set; }
        public Nullable<decimal> SetupLaborCurrent { get; set; }
        public string CostComponent { get; set; }
        public string ActivityBasedCostingActivityCode { get; set; }
        public Nullable<decimal> AssetItemNumber { get; set; }
        public Nullable<decimal> AmountUnaccountedScrap { get; set; }
        public Nullable<decimal> UnitsUnaccountedScrap { get; set; }
        public Nullable<decimal> HoursUnaccountedDirectLabor { get; set; }
        public Nullable<decimal> RunLaborRate { get; set; }
        public Nullable<decimal> RunMachineRate { get; set; }
        public Nullable<decimal> SetupLaborRate { get; set; }
        public string ConstraintsFlag { get; set; }
        public Nullable<decimal> TimeScheduledStartHHMMSS { get; set; }
        public Nullable<decimal> TimeScheduledEndHHMMSS { get; set; }
        public Nullable<decimal> TimeCompleted { get; set; }
        public Nullable<int> DateActualStart { get; set; }
        public Nullable<decimal> TimeStartHHMMSS { get; set; }
        public string CompetencyType { get; set; }
        public string CompetencyCode { get; set; }
        public Nullable<decimal> CompetencyLevelFrom { get; set; }
        public Nullable<decimal> CompetencyLevelTo { get; set; }
        public string RuleMatchFlag { get; set; }
        public Nullable<decimal> AddressNumberManager { get; set; }
        public Nullable<decimal> Supervisor { get; set; }
        public Nullable<decimal> AddressNumberAssignedTo { get; set; }
        public string MaintenanceScheduleFlag { get; set; }
        public string ResourcesAssigned { get; set; }
    }
}
