//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderPart
    {
        public Nullable<decimal> WorkOrderID { get; set; }
        public string OrderType { get; set; }
        public string OrderSuffix { get; set; }
        public string TypeBillofMaterial { get; set; }
        public string FixedorVariableQuantity { get; set; }
        public string IssueTypeCode { get; set; }
        public string CoProductsByProductsIntermediate { get; set; }
        public string ComponentType { get; set; }
        public Nullable<decimal> ComponentLineNumber { get; set; }
        public Nullable<decimal> FromPotency { get; set; }
        public Nullable<decimal> ThruPotency { get; set; }
        public string FromGrade { get; set; }
        public string ThruGrade { get; set; }
        public string CompanyKeyRelatedOrder { get; set; }
        public string RelatedPOSOWONumber { get; set; }
        public string RelatedPOSOWOOrderType { get; set; }
        public Nullable<decimal> RelatedPOSOLineNumber { get; set; }
        public Nullable<decimal> SequenceNumberOperations { get; set; }
        public Nullable<decimal> SequenceBubbleSequence { get; set; }
        public Nullable<decimal> ResourcePercent { get; set; }
        public Nullable<decimal> PercentPercentofScrap { get; set; }
        public Nullable<decimal> PercentRework { get; set; }
        public Nullable<decimal> PercentAsis { get; set; }
        public Nullable<decimal> PercentCumulativePlannedYield { get; set; }
        public Nullable<decimal> OperationScrapPercent { get; set; }
        public Nullable<decimal> LeadtimeOffsetDays { get; set; }
        public Nullable<decimal> ComponentItemNumberShort { get; set; }
        public string Component2ndItemNumber { get; set; }
        public string Component3rdItemNumber { get; set; }
        public string ComponentBranch { get; set; }
        public string Description { get; set; }
        public string DescriptionLine2 { get; set; }
        public string Location { get; set; }
        public string LotSerialNumber { get; set; }
        public Nullable<decimal> AddressNumber { get; set; }
        public string LineType { get; set; }
        public string SerialNumberLot { get; set; }
        public Nullable<int> DateOrderTransaction { get; set; }
        public Nullable<int> DateRequested { get; set; }
        public Nullable<decimal> UnitsOrderTransactionQuantity { get; set; }
        public Nullable<decimal> QuantityAvailable { get; set; }
        public Nullable<decimal> UnitsQuantityCanceledScrapped { get; set; }
        public Nullable<decimal> UnitsQtyBackorderedHeld { get; set; }
        public Nullable<decimal> HoursUnaccountedDirectLabor { get; set; }
        public Nullable<decimal> UnitsQuantityCommited { get; set; }
        public string UnitofMeasure { get; set; }
        public Nullable<decimal> AmountEstimatedCost { get; set; }
        public string RouteSheetN { get; set; }
        public string MaterialStatusCodeWO { get; set; }
        public string DocumentType { get; set; }
        public string MessageNumber { get; set; }
        public string BusinessUnit { get; set; }
        public string ProjectBusinessUnit { get; set; }
        public string ObjectAccount { get; set; }
        public string Subsidiary { get; set; }
        public string ComponentRevisionLevel { get; set; }
        public Nullable<int> DateCompletionJulian { get; set; }
        public string NumberParentWONumber { get; set; }
        public string CommittedHS { get; set; }
        public string UserReservedCode { get; set; }
        public Nullable<int> UserReservedDate { get; set; }
        public Nullable<decimal> UserReservedAmount { get; set; }
        public string UserReservedReference { get; set; }
        public Nullable<decimal> UserReservedNumber { get; set; }
        public string UserID { get; set; }
        public string ProgramID { get; set; }
        public string WorkStationID { get; set; }
        public Nullable<int> DateUpdated { get; set; }
        public Nullable<decimal> TimeofDay { get; set; }
        public decimal ID { get; set; }
        public Nullable<decimal> PrimaryLastSupplierNumber { get; set; }
        public string IssueandReceipt { get; set; }
        public Nullable<decimal> AmountUnaccountedDirectLabor { get; set; }
        public Nullable<decimal> AmountUnaccountedScrap { get; set; }
        public Nullable<decimal> UnitsUnaccountedScrap { get; set; }
        public Nullable<int> GLDate { get; set; }
        public string PartsListSubstituteFlag { get; set; }
        public string ActiveIngredientFlag { get; set; }
        public Nullable<decimal> SecondaryQuantityIssuedCompleted { get; set; }
        public string UnitofMeasureSecondary { get; set; }
        public string ConstraintsFlag { get; set; }
        public Nullable<decimal> PickSlipNumber { get; set; }
        public Nullable<int> LotEffectivityDate { get; set; }
        public string CostComponent { get; set; }
        public string CriticalHoldPropagation { get; set; }
        public Nullable<decimal> ComponentLineNumberBOM { get; set; }
        public string BubbleSequenceAlphaNumeric { get; set; }
    }
}
