//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.WSJDEData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WSJDE : DbContext
    {
       
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Location> Locations { get; set; }
        public DbSet<UserDefinedCodeType> UserDefinedCodeTypes { get; set; }
        public DbSet<UserDefinedCode> UserDefinedCodes { get; set; }
        public DbSet<BusinessUnit> BusinessUnits { get; set; }
        public DbSet<OMBOrderHeader> OMBOrderHeaders { get; set; }
        public DbSet<OMBUnit> OMBUnits { get; set; }
        public DbSet<AddressBook> AddressBooks { get; set; }
        public DbSet<Asset> Assets { get; set; }
        public DbSet<Equipment> Equipments { get; set; }
        public DbSet<WorkOrderPart> WorkOrderParts { get; set; }
        public DbSet<WorkOrderActivity> WorkOrderActivities { get; set; }
        public DbSet<PartExtension> PartExtensions { get; set; }
        public DbSet<RoutingExtension> RoutingExtensions { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<ItemBranch> ItemBranches { get; set; }
        public DbSet<ItemCost> ItemCosts { get; set; }
        public DbSet<WorkOrder> WorkOrders { get; set; }
        public DbSet<WorkOrderMasterTag> WorkOrderMasterTags { get; set; }
        public DbSet<WorkOrderInstruction> WorkOrderInstructions { get; set; }
        public DbSet<CustomAsset> CustomAssets { get; set; }
        public DbSet<LaborActivity> LaborActivities { get; set; }
        public DbSet<OMBWorkOrder> OMBWorkOrders { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<OMBFleetCategory> OMBFleetCategories { get; set; }
        public DbSet<FleetAttribute> FleetAttributes { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<Security> Securities { get; set; }
        public DbSet<MWOFeithImage> MWOFeithImages { get; set; }
        public DbSet<OMBLookup> OMBLookups { get; set; }
        public DbSet<TemporaryWorkOrderNumber> TemporaryWorkOrderNumbers { get; set; }
        public DbSet<PaperlessRequest> PaperlessRequests { get; set; }
        public DbSet<PaperlessRequestOrder> PaperlessRequestOrders { get; set; }
        public DbSet<APIRequestData> APIRequestDatas { get; set; }
        public DbSet<APIRequestDataKey> APIRequestDataKeys { get; set; }
        public DbSet<APIRequestDataKeyClass> APIRequestDataKeyClasses { get; set; }
        public DbSet<APIRequestSource> APIRequestSources { get; set; }
        public DbSet<APISource> APISources { get; set; }
        public DbSet<APIRequest> APIRequests { get; set; }
        public DbSet<APISFProduct> APISFProducts { get; set; }
        public DbSet<Inventory> Inventories { get; set; }
        public DbSet<InventoryProduct> InventoryProducts { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }
        public DbSet<ProductCategoryStatus> ProductCategoryStatuses { get; set; }
        public DbSet<ProductStatus> ProductStatuses { get; set; }
        public DbSet<SecurityLevel> SecurityLevels { get; set; }
    }
}
