//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.ASJDE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASJDE : DbContext
    {
        public ASJDE()
            : base("name=ASJDE")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<VideoArea> VideoAreas { get; set; }
        public DbSet<VideoGroup> VideoGroups { get; set; }
        public DbSet<VideoLog> VideoLogs { get; set; }
        public DbSet<Video> Videos { get; set; }
        public DbSet<SafetyIncidentCause> SafetyIncidentCauses { get; set; }
        public DbSet<SafetyIncidentCauseCategory> SafetyIncidentCauseCategories { get; set; }
        public DbSet<SafetyIncidentEmployeeType> SafetyIncidentEmployeeTypes { get; set; }
        public DbSet<SafetyIncidentOutcome> SafetyIncidentOutcomes { get; set; }
        public DbSet<SafetyIncidentSiteCategory> SafetyIncidentSiteCategories { get; set; }
        public DbSet<SafetyIncidentStatus> SafetyIncidentStatus { get; set; }
        public DbSet<SafetyIncidentType> SafetyIncidentTypes { get; set; }
        public DbSet<SafetyIncidentUnsafeAct> SafetyIncidentUnsafeActs { get; set; }
        public DbSet<SafetyIncident> SafetyIncidents { get; set; }
        public DbSet<Entity> Entities { get; set; }
        public DbSet<EntityStatus> EntityStatus { get; set; }
        public DbSet<Branch> Branches { get; set; }
        public DbSet<BusinessUnit> BusinessUnits { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<Depot> Depots { get; set; }
        public DbSet<HoursWorked> HoursWorkeds { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<LocationStatus> LocationStatus { get; set; }
        public DbSet<OperationalBusinessUnit> OperationalBusinessUnits { get; set; }
        public DbSet<StrategicBusinessUnit> StrategicBusinessUnits { get; set; }
    }
}
