//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.ASJDE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.HoursWorked = new HashSet<HoursWorked>();
            this.Location = new HashSet<Location>();
            this.AS_SAFETY_INCIDENT = new HashSet<SafetyIncident>();
        }
    
        public decimal ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<HoursWorked> HoursWorked { get; set; }
        public virtual ICollection<Location> Location { get; set; }
        public virtual ICollection<SafetyIncident> AS_SAFETY_INCIDENT { get; set; }
    }
}
