//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.ASJDE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Entity = new HashSet<Entity>();
            this.HoursWorked = new HashSet<HoursWorked>();
            this.AS_SAFETY_INCIDENT = new HashSet<SafetyIncident>();
        }
    
        public decimal ID { get; set; }
        public decimal LocationStatusID { get; set; }
        public decimal CurrencyID { get; set; }
        public decimal CountryID { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Description { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<Entity> Entity { get; set; }
        public virtual ICollection<HoursWorked> HoursWorked { get; set; }
        public virtual LocationStatus LocationStatus { get; set; }
        public virtual ICollection<SafetyIncident> AS_SAFETY_INCIDENT { get; set; }
    }
}
