//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.ASJDE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafetyIncident
    {
        public decimal ID { get; set; }
        public Nullable<decimal> StatusID { get; set; }
        public Nullable<decimal> EmployeeTypeID { get; set; }
        public Nullable<decimal> SiteCategoryID { get; set; }
        public Nullable<decimal> TypeID { get; set; }
        public Nullable<decimal> OutcomeID { get; set; }
        public Nullable<decimal> UnsafeActID { get; set; }
        public Nullable<decimal> CauseCategoryID { get; set; }
        public Nullable<decimal> CauseID { get; set; }
        public Nullable<System.DateTime> DateOfIncident { get; set; }
        public string EmployeeName { get; set; }
        public string Title { get; set; }
        public string WorkRelated { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> DaysAwayFromWork { get; set; }
        public Nullable<decimal> DaysTransferredRestricted { get; set; }
        public string ReturnToWork { get; set; }
        public Nullable<System.DateTime> DateReturnedToWork { get; set; }
        public string RootCause { get; set; }
        public string CorrectiveAction { get; set; }
        public string ResponsiblePerson { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Complete { get; set; }
        public string Recordable { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedByUserName { get; set; }
        public Nullable<System.DateTime> DateReturnedToWorkRestricted { get; set; }
        public Nullable<decimal> PIBID { get; set; }
        public decimal CountryID { get; set; }
        public decimal LocationID { get; set; }
        public string LocationSite { get; set; }
        public Nullable<decimal> EntityID { get; set; }
    
        public virtual SafetyIncidentCause SafetyIncidentCause { get; set; }
        public virtual SafetyIncidentCauseCategory SafetyIncidentCauseCategory { get; set; }
        public virtual SafetyIncidentEmployeeType SafetyIncidentEmployeeType { get; set; }
        public virtual SafetyIncidentOutcome SafetyIncidentOutcome { get; set; }
        public virtual SafetyIncidentSiteCategory SafetyIncidentSiteCategory { get; set; }
        public virtual SafetyIncidentStatus SafetyIncidentStatus { get; set; }
        public virtual SafetyIncidentType SafetyIncidentType { get; set; }
        public virtual SafetyIncidentUnsafeAct SafetyIncidentUnsafeAct { get; set; }
        public virtual Country Country { get; set; }
        public virtual Location Location { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
