//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.ASJDE
{
    using System;
    using System.Collections.Generic;
    
    public partial class StrategicBusinessUnit
    {
        public StrategicBusinessUnit()
        {
            this.OperationalBusinessUnit = new HashSet<OperationalBusinessUnit>();
            this.VideoArea = new HashSet<VideoArea>();
        }
    
        public decimal ID { get; set; }
        public decimal CompanyID { get; set; }
        public decimal EntityID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual ICollection<OperationalBusinessUnit> OperationalBusinessUnit { get; set; }
        public virtual ICollection<VideoArea> VideoArea { get; set; }
    }
}
