//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.ASJDE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoLog
    {
        public decimal ID { get; set; }
        public Nullable<decimal> VideoID { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
