//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.ASJDE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoArea
    {
        public VideoArea()
        {
            this.VideoGroup = new HashSet<VideoGroup>();
        }
    
        public decimal ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> CompanyID { get; set; }
        public Nullable<decimal> StrategicBusinessUnitID { get; set; }
        public Nullable<decimal> OperationalBusinessUnitID { get; set; }
        public Nullable<decimal> BusinessUnitID { get; set; }
        public Nullable<decimal> BranchID { get; set; }
        public Nullable<decimal> DepotID { get; set; }
    
        public virtual ICollection<VideoGroup> VideoGroup { get; set; }
        public virtual Branch AS_BRANCH { get; set; }
        public virtual BusinessUnit AS_BUSINESS_UNIT { get; set; }
        public virtual Company AS_COMPANY { get; set; }
        public virtual Depot AS_DEPOT { get; set; }
        public virtual OperationalBusinessUnit AS_OP_BUSINESS_UNIT { get; set; }
        public virtual StrategicBusinessUnit AS_STRATEGIC_BUSINESS_UNIT { get; set; }
    }
}
