//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.ASJDE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public decimal ID { get; set; }
        public decimal VideoGroupID { get; set; }
        public string Name { get; set; }
        public decimal ReferenceID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedByUser { get; set; }
    
        public virtual VideoGroup VideoGroup { get; set; }
    }
}
