//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Framework.ASJDE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoGroup
    {
        public VideoGroup()
        {
            this.Video = new HashSet<Video>();
        }
    
        public decimal ID { get; set; }
        public decimal VideoAreaID { get; set; }
        public string Name { get; set; }
    
        public virtual VideoArea VideoArea { get; set; }
        public virtual ICollection<Video> Video { get; set; }
    }
}
